# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Weather Data API
  description: weather
  version: "0.0.1"
  termsOfService: "weather"
# the domain of the service
host: weather.kyper.co
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v0
produces:
  - application/json
paths:
  /station_list:
    get:
      operationId: "station_list"
      summary: Search weather stations information by country or geo information
      description: |
        Search weather stations information by country or geo information.
      parameters:
        - name: country
          in: query
          description: |
            The country to search for. For example: US. Refer to ftp://ftp.ncdc.noaa.gov/pub/data/noaa/country-list.txt
          required: false
          type: string
        - name: lat
          in: query
          description: The latitude of geo information
          required: false
          type: integer
          format: int32
        - name: lng
          in: query
          description: The longitude of geo information
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: The pandas.DataFrame of news
          schema:
            $ref: '#/definitions/DataFrame'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
  /weather_stations:
    get:
      operationId: "weather_stations"
      summary: Search weather data by stations Id
      description: |
        Search weather data by station Id and date range.
      parameters:
        - name: stations
          in: query
          description: stations id to search for
          required: true
          type: array
          items: {
              type: string
            }
        - name: start_date
          in: query
          description: The optional start date for the query
          required: true
          type: string
        - name: end_date
          in: query
          description: The optional end date for the query
          required: true
          type: string
        - name: fields
          in: query
          description: The optional, fields for the query
          defaultValue: 123
          type: array
          items: {
              type: string
            }
        - name: freq
          in: query
          description: |
            The optional,
            'd': daily summary of weather (default),
            'w': weekly summary of weather, 
            'm': monthly summary of weather
          defaultValue: d
          type: string
      responses:
        200:
          description: The pandas.DataFrame of weather data
          schema:
            $ref: '#/definitions/DataFrame'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
            
  /get_fields:
    get:
      operationId: "get_fields"
      summary: List all fields provided by weather data API.
      description: all fields provided by weather data API.
      responses:
        200:
          description: The pandas.DataFrame of weather data
          schema:
            $ref: '#/definitions/pandas.DataFrame'
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'        

definitions:
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  pandas.DataFrame:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Response:
    properties:
      code:
        type: string
      data:
        items:
          $ref: '#/definitions/DataFrame'
